### ISSUE TITLE
can we make `XRDepthStateInit` optional?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/depth-sensing#46]
The depth sensing spec states that [XRDepthStateInit](XRDepthStateInit](https://immersive-web.github.io/depth-sensing/#dictdef-xrdepthstateinit) is required; even when the user doesn't set any values.
Can we make it optional instead?

Quest browser has it as optional and this is causing issues in [three.js](https://github.com/mrdoob/three.js/issues/23881)

/agenda can we make `XRDepthStateInit` optional?

**Comment by alcooper91** [comment]
Worth a mention that the samples don't appear to be supplying the XRDepthStateInit which is causing issues for Chrome at the moment since we *do* require it, so if we decide not to relax this, there's an AI to update the samples: https://immersive-web.github.io/webxr-samples/proposals/phone-ar-depth.html

**Comment by alcooper91** [comment]
Note that I'm also not sure about:

> even when the user doesn't set any values

based on the algorithm here that essentially requires the returned usage/format to be contained in the array, so if the arrays are empty, no depth sensing session should be started:
https://immersive-web.github.io/depth-sensing/#find-supported-configuration-combination
